###

# curl -X POST https://your-api-endpoint.com/api/products 
#  -H "Content-Type: application/json" 
#  -d '{
#    "title": "Example Product",
#    "description": "This is an example product.",
#    "price": 100,
#    "categoryId": 1,   1: Kitchen, 2: Living Room, 3: Decoration, 4: Guest Room, 5: Dining Room, 6: Bed Room
#    "stock": 10,
#    "weight": 1.2,
#    "height": 10,
#    "width": 20,
#    "depth": 30,
#    "qrCode": "QR12345",
#    "barCode": "BAR12345",
#    "images": ["image1.jpg", "image2.jpg"],
#    "thumbnail": "thumbnail.jpg"
#  }'
POST https://gd-store.ge/api/Product
Content-Type: application/json

{
  "title": "Example Product",
  "description": "This is an example product.",
  "price": 100,
  "categoryId": 1,
  "stock": 10,
  "weight": 1.2,
  "height": 10,
  "width": 20,
  "depth": 30,
  "qrCode": "QR12345",
  "barCode": "BAR12345",
  "images": [
    "image1.jpg",
    "image2.jpg"
  ],
  "thumbnail": "thumbnail.jpg"
}



###

